base:
  base_info_url: https://XXX.com
  base_php_url: https://XXX.com
  base_weixin_url: https://XXX.com
  base_fenmi_url: https://XXX.com
#  base_czt_url:https://XXX.com
  base_czt_url: https://XXX.com
log:
  log_name: logs_
  log_level: info
  log_format: '[%(asctime)s] %(filename)s->%(funcName)s line:%(lineno)d [%(levelname)s] %(message)s'
